# Generated by Django 5.2.3 on 2025-06-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoSugerido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('novato', 'Novato'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15)),
                ('genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('mixto', 'Mixto')], max_length=10)),
                ('disponibilidad', models.JSONField(help_text='Días y horarios sugeridos')),
                ('fecha_sugerencia', models.DateTimeField(auto_now_add=True)),
                ('criterios', models.JSONField(blank=True, help_text='Criterios de emparejamiento usados', null=True)),
                ('jugadores', models.ManyToManyField(to='club.jugador')),
            ],
        ),
    ]
