# Generated by Django 5.2.3 on 2025-06-18 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_notificacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gruposugerido',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('reservado', 'Reservado')], default='nuevo', max_length=10),
        ),
        migrations.AddField(
            model_name='gruposugerido',
            name='sugerido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_sugeridos', to=settings.AUTH_USER_MODEL),
        ),
    ]
