# Generated by Django 5.2.3 on 2025-06-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0003_gruposugerido_estado_gruposugerido_sugerido_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gruposugerido',
            name='disponibilidad',
            field=models.JSONField(help_text='Día sugerido para el grupo'),
        ),
    ]
