# Generated by Django 5.2.3 on 2025-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0004_alter_gruposugerido_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(default='info', max_length=50),
        ),
    ]
