# Generated by Django 5.2.3 on 2025-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.PositiveIntegerField(blank=True, help_text='En gramos (solo paletas)', null=True),
        ),
    ]
