# Generated by Django 5.2.3 on 2025-06-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0003_caja_movimientocaja'),
    ]

    operations = [
    ]
