# Generated by Django 5.2.3 on 2025-06-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0004_auto_20250622_1726'),
    ]

    operations = [
    ]
