# Generated by Django 5.2.3 on 2025-06-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_multimedia_remove_venta_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimonios/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
