# Generated by Django 5.2.3 on 2025-06-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_jugador_en_tinder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nivel', models.CharField(choices=[('novato', 'Novato'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15)),
                ('preferencia_genero', models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer'), ('mixto', 'Mixto')], max_length=10)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='club.jugador')),
            ],
            options={
                'unique_together': {('jugador', 'dia', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
