# Generated by Django 5.2.3 on 2025-06-19 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_disponibilidadjugador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='disponibilidad',
        ),
    ]
