# Generated by Django 5.2.3 on 2025-06-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_remove_jugador_disponibilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='jugador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='club.jugador'),
        ),
    ]
