# Generated by Django 5.2.3 on 2025-06-20 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_reserva_jugador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sitio', models.CharField(default='Club de Pádel', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('color_primario', models.CharField(default='#2563eb', help_text='Color principal (hex)', max_length=7)),
                ('color_secundario', models.CharField(default='#facc15', help_text='Color secundario (hex)', max_length=7)),
                ('mensaje_bienvenida', models.CharField(blank=True, max_length=200, null=True)),
                ('mensaje_footer', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Branding (colores, logo, mensajes)',
                'verbose_name_plural': 'Branding (colores, logo, mensajes)',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('stock', 'Stock'), ('reserva', 'Reserva'), ('pago', 'Pago'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('objeto_id', models.CharField(blank=True, max_length=64, null=True)),
                ('objeto_tipo', models.CharField(blank=True, max_length=64, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(default='efectivo', max_length=50)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='club.jugador')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='club.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('jugadores', models.ManyToManyField(related_name='torneos', to='club.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('puntaje_jugador1', models.PositiveIntegerField(default=0)),
                ('puntaje_jugador2', models.PositiveIntegerField(default=0)),
                ('finalizado', models.BooleanField(default=False)),
                ('jugador1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_jugador1', to='club.jugador')),
                ('jugador2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_jugador2', to='club.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='club.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.jugador')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='club.torneo')),
            ],
            options={
                'ordering': ['-puntos'],
                'unique_together': {('torneo', 'jugador')},
            },
        ),
    ]
