# Generated by Django 5.2.3 on 2025-06-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_brandingconfig_auditoria_pago_torneo_partidotorneo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='reserva',
        ),
        migrations.AddField(
            model_name='jugador',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Foto de perfil del jugador', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, default=None, max_length=100),
            preserve_default=False,
        ),
    ]
