# Generated by Django 4.2 on 2025-06-21 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_remove_pago_reserva_jugador_avatar_pago_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='disponible', max_length=10),
        ),
    ]
