# Generated by Django 4.2 on 2025-06-21 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_alter_reserva_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciasEmparejamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='¿Buscar emparejamientos activamente?')),
                ('nivel_juego', models.CharField(choices=[('novato', 'Novato'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=15)),
                ('preferencia_genero', models.CharField(choices=[('hombres', 'Solo Hombres'), ('mujeres', 'Solo Mujeres'), ('mixto', 'Mixto')], max_length=10)),
                ('jugador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_emparejamiento', to='club.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='EmparejamientoEncontrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('nivel', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('jugadores', models.ManyToManyField(related_name='emparejamientos', to='club.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadEmparejamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miercoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('preferencias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='club.preferenciasemparejamiento')),
            ],
            options={
                'unique_together': {('preferencias', 'dia', 'hora_inicio')},
            },
        ),
    ]
