# Generated by Django 4.2 on 2025-06-21 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_preferenciasemparejamiento_emparejamientoencontrado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emparejamientoencontrado',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emparejamientoencontrado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado')], default='pendiente', max_length=15),
        ),
        migrations.CreateModel(
            name='ConfirmacionEmparejamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('emparejamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmaciones', to='club.emparejamientoencontrado')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.jugador')),
            ],
            options={
                'unique_together': {('emparejamiento', 'jugador')},
            },
        ),
    ]
