# Generated by Django 4.2 on 2025-06-21 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_emparejamientoencontrado_fecha_expiracion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emparejamientoencontrado',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emparejamiento', to='club.reserva'),
        ),
        migrations.AlterField(
            model_name='emparejamientoencontrado',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('notificado', 'Notificado'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('reservado', 'Reservado')], default='pendiente', max_length=15),
        ),
    ]
