# Generated by Django 5.2.3 on 2025-06-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0015_emparejamientoencontrado_reserva_and_more'),
    ]

    operations = [
    ]
