# Generated by Django 5.2.3 on 2025-06-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_auto_20250622_1927'),
    ]

    operations = [
    ]
