# Generated by Django 5.2.3 on 2025-06-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ventas', '0001_initial'),
    ]

    operations = [
    ]
