# Generated by Django 5.2.3 on 2025-06-22 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ventas', '0002_auto_20250622_1726'),
    ]

    operations = [
    ]
