# Generated by Django 5.2.3 on 2025-06-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ventas', '0003_auto_20250622_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('descuento_porcentaje', 'Descuento Porcentaje'), ('descuento_fijo', 'Descuento Fijo'), ('2x1', '2x1'), ('puntos_dobles', 'Puntos Dobles')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, help_text='Porcentaje o monto fijo', max_digits=10)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='stock_venta_sku_f8d83c_idx',
            old_name='stock_venta_sku_b8e5c8_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='stock_venta_categor_3efa46_idx',
            old_name='stock_venta_categor_c8b2b1_idx',
        ),
        migrations.RenameIndex(
            model_name='producto',
            new_name='stock_venta_activo_a10b8d_idx',
            old_name='stock_venta_activo_b5c8a1_idx',
        ),
        migrations.AddField(
            model_name='promocion',
            name='productos',
            field=models.ManyToManyField(blank=True, to='stock_ventas.producto'),
        ),
    ]
