# Generated by Django 5.2.3 on 2025-06-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ventas', '0004_cliente_promocion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
